# Generated by Django 5.2 on 2025-04-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "VENDOR"), (2, "CUSTOMER")], null=True
            ),
        ),
    ]
