# Generated by Django 5.2 on 2025-06-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_age_user_length_user_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('Erkek', 'Erkek'), ('Kadin', 'Kadin')], max_length=10, null=True),
        ),
    ]
