# Generated by Django 5.2 on 2025-05-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
