# Generated by Django 5.2 on 2025-05-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0002_alter_category_slug_alter_fooditem_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
