# Generated by Django 5.2 on 2025-05-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
    ]
